name: Setup Risor
description: Installs Risor
branding:
  icon: chevron-right
  color: black
inputs:
  cache:
    description: Cache dependencies
    required: false
    default: "true"
  version:
    description: Version of Risor to install
    required: true
    default: "latest"
runs:
  using: node20
  main: dist/index.js
