name: Test action

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Risor
        uses: ./

      - shell: risor {0}
        run: |
          array := ["gophers", "are", "burrowing", "rodents"]

          sentence := array | strings.join(" ") | strings.to_upper

          print(sentence)
